services:
  microsoft-rewards-script:
    build: .
    container_name: netsky
    environment:
      - TZ=America/Toronto #change to your local timezone
      - NODE_ENV=production 
      - HEADLESS=true #do not change
      ### the following are optional, you only need to include them if you want to enter a custom value, removing them will use the default values
      - BASE_URL=https://rewards.bing.com
      - SESSION_PATH=sessions
      - RUN_ON_ZERO_POINTS=false
      - CLUSTERS=1
      - SAVE_FINGERPRINT=false
      - WORKERS_DO_DAILY_SET=true
      - WORKERS_DO_MORE_PROMOTIONS=true
      - WORKERS_DO_PUNCH_CARDS=true
      - WORKERS_DO_DESKTOP_SEARCH=true
      - WORKERS_DO_MOBILE_SEARCH=true
      - SEARCH_SETTINGS_USE_GEO_LOCALE_QUERIES=false
      - SEARCH_SETTINGS_SCROLL_RANDOM_RESULTS=true
      - SEARCH_SETTINGS_CLICK_RANDOM_RESULTS=true
      - SEARCH_SETTINGS_SEARCH_DELAY_MIN=10000 # Set the search delay longer, e.g. MIN=180000 and MAX=270000 if you live in a region where MS enforces a search cooldown
      - SEARCH_SETTINGS_SEARCH_DELAY_MAX=20000
      - SEARCH_SETTINGS_RETRY_MOBILE_SEARCH=true
      - WEBHOOK_ENABLED=false
      - WEBHOOK_URL=
      ### Customize your run schedule, default 5:00 am and 11:00 am, use crontab.guru if you're not sure 
      - CRON_START_TIME=0 5,11 * * *
      ### Run on start, set as false to only run the script per the cron schedule
      - RUN_ON_START=true 
    restart: unless-stopped
    volumes:
      - .:/usr/src/microsoft-rewards-script
